DetectionSetGroup = SET_GROUP:New()
DetectionSetGroup:FilterPrefixes( { "EWR" } )
DetectionSetGroup:FilterStart()
Detection = DETECTION_AREAS:New( DetectionSetGroup, 35000 )
A2aDispatcher = AI_A2A_DISPATCHER:New( Detection )
A2aDispatcher:SetEngageRadius( 30000 )
A2aDispatcher:SetGciRadius( 15000 )
A2aDispatcher:SetSquadron( "CAP1", AIRBASE.Syria.Akrotiri, { "AGGRESSOR 1" }, 10 )
A2aDispatcher:SetSquadron( "CAP2", AIRBASE.Syria.Akrotiri, { "AGGRESSOR 2" }, 10 )
A2aDispatcher:SetSquadron( "CAPHELY1", AIRBASE.Syria.Akrotiri, { "HELY 1" }, 10 )
A2aDispatcher:SetSquadron( "CAPHELY2", AIRBASE.Syria.Akrotiri, { "HELY 2" }, 10 )
A2aDispatcher:SetSquadronGrouping( "CAP1", 3 )
A2aDispatcher:SetSquadronGrouping( "CAP2", 3 )
A2aDispatcher:SetSquadronGrouping( "CAPHELY1", 2 )
A2aDispatcher:SetSquadronGrouping( "CAPHELY2", 2 )
A2aDispatcher:SetDefaultFuelThreshold( 0.4 )
A2aDispatcher:SetSquadronTakeoffFromParkingCold( "CAP1" )
A2aDispatcher:SetSquadronTakeoffFromParkingCold( "CAP2" )
A2aDispatcher:SetSquadronTakeoffFromParkingCold( "CAPHELY1" )
A2aDispatcher:SetSquadronTakeoffFromParkingCold( "CAPHELY2" )
A2aDispatcher:SetSquadronLandingAtEngineShutdown( "CAP1" )
A2aDispatcher:SetSquadronLandingAtEngineShutdown( "CAP2" )
A2aDispatcher:SetSquadronLandingAtEngineShutdown( "CAPHELY1" )
A2aDispatcher:SetSquadronLandingAtEngineShutdown( "CAPHELY2" )
CAPZone1 = ZONE:New( "CAP ZONE HELY 1" )
CAPZone2 = ZONE:New( "CAP ZONE HELY 2" )
CAPZone3 = ZONE:New( "CAP ZONE AERO 1" )
CAPZone4 = ZONE:New( "CAP ZONE AERO 2" )
A2aDispatcher:SetGciRadius( 15000 )
A2aDispatcher:SetSquadronCap( "CAP1", CAPZone3, 6000, 10000, 550, 750, 800, 1200, "BARO" )
A2aDispatcher:SetSquadronCapInterval( "CAP1", 1, 30, 300, 1 )
A2aDispatcher:SetSquadronCap( "CAP2", CAPZone4, 6000, 10000, 550, 750, 800, 1200, "BARO" )
A2aDispatcher:SetSquadronCapInterval( "CAP2", 1, 30, 300, 1 )
A2aDispatcher:SetSquadronCap( "CAPHELY1", CAPZone1, 200, 500, 70, 100, 70, 90, "BARO" )
A2aDispatcher:SetSquadronCapInterval( "CAPHELY1", 1, 30, 200, 1 )
A2aDispatcher:SetSquadronCap( "CAPHELY2", CAPZone2, 200, 500, 70, 100, 70, 90, "BARO" )
A2aDispatcher:SetSquadronCapInterval( "CAPHELY2", 1, 30, 200, 1 )